server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity-service"
    username: root
    password: ""
  application:
    name: identity-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  singerKey: "Fsqn44tSG/pN+y6DVO9886UQkzBJcmNk+wle3o35Th4PY2nV2xtvPjAX3cYMO1/W\n"
  valid-duration: 3600 #in seconds
  refreshable-duration: 360000 # in seconds
